enum ErrorCode {
  UNKNOWN_ERROR,
  NATIVE_AUTH_STRATEGY_ERROR,
  INVALID_CREDENTIALS_ERROR,
  ORDER_STATE_TRANSITION_ERROR,
  EMAIL_ADDRESS_CONFLICT_ERROR,
  GUEST_CHECKOUT_ERROR,
  ORDER_LIMIT_ERROR,
  NEGATIVE_QUANTITY_ERROR,
  INSUFFICIENT_STOCK_ERROR,
  COUPON_CODE_INVALID_ERROR,
  COUPON_CODE_EXPIRED_ERROR,
  COUPON_CODE_LIMIT_ERROR,
  ORDER_MODIFICATION_ERROR,
  INELIGIBLE_SHIPPING_METHOD_ERROR,
  NO_ACTIVE_ORDER_ERROR,
  ORDER_PAYMENT_STATE_ERROR,
  INELIGIBLE_PAYMENT_METHOD_ERROR,
  PAYMENT_FAILED_ERROR,
  PAYMENT_DECLINED_ERROR,
  ALREADY_LOGGED_IN_ERROR,
  MISSING_PASSWORD_ERROR,
  PASSWORD_VALIDATION_ERROR,
  PASSWORD_ALREADY_SET_ERROR,
  VERIFICATION_TOKEN_INVALID_ERROR,
  VERIFICATION_TOKEN_EXPIRED_ERROR,
  IDENTIFIER_CHANGE_TOKEN_INVALID_ERROR,
  IDENTIFIER_CHANGE_TOKEN_EXPIRED_ERROR,
  PASSWORD_RESET_TOKEN_INVALID_ERROR,
  PASSWORD_RESET_TOKEN_EXPIRED_ERROR,
  NOT_VERIFIED_ERROR
}

ErrorCode parseErrorCode(String code) {
  switch (code) {
    case 'UNKNOWN_ERROR':
      return ErrorCode.UNKNOWN_ERROR;
    case 'NATIVE_AUTH_STRATEGY_ERROR':
      return ErrorCode.NATIVE_AUTH_STRATEGY_ERROR;
    case 'INVALID_CREDENTIALS_ERROR':
      return ErrorCode.INVALID_CREDENTIALS_ERROR;
    case 'ORDER_STATE_TRANSITION_ERROR':
      return ErrorCode.ORDER_STATE_TRANSITION_ERROR;
    case 'EMAIL_ADDRESS_CONFLICT_ERROR':
      return ErrorCode.EMAIL_ADDRESS_CONFLICT_ERROR;
    case 'GUEST_CHECKOUT_ERROR':
      return ErrorCode.GUEST_CHECKOUT_ERROR;
    case 'ORDER_LIMIT_ERROR':
      return ErrorCode.ORDER_LIMIT_ERROR;
    case 'NEGATIVE_QUANTITY_ERROR':
      return ErrorCode.NEGATIVE_QUANTITY_ERROR;
    case 'INSUFFICIENT_STOCK_ERROR':
      return ErrorCode.INSUFFICIENT_STOCK_ERROR;
    case 'COUPON_CODE_INVALID_ERROR':
      return ErrorCode.COUPON_CODE_INVALID_ERROR;
    case 'COUPON_CODE_EXPIRED_ERROR':
      return ErrorCode.COUPON_CODE_EXPIRED_ERROR;
    case 'COUPON_CODE_LIMIT_ERROR':
      return ErrorCode.COUPON_CODE_LIMIT_ERROR;
    case 'ORDER_MODIFICATION_ERROR':
      return ErrorCode.ORDER_MODIFICATION_ERROR;
    case 'INELIGIBLE_SHIPPING_METHOD_ERROR':
      return ErrorCode.INELIGIBLE_SHIPPING_METHOD_ERROR;
    case 'NO_ACTIVE_ORDER_ERROR':
      return ErrorCode.NO_ACTIVE_ORDER_ERROR;
    case 'ORDER_PAYMENT_STATE_ERROR':
      return ErrorCode.ORDER_PAYMENT_STATE_ERROR;
    case 'INELIGIBLE_PAYMENT_METHOD_ERROR':
      return ErrorCode.INELIGIBLE_PAYMENT_METHOD_ERROR;
    case 'PAYMENT_FAILED_ERROR':
      return ErrorCode.PAYMENT_FAILED_ERROR;
    case 'PAYMENT_DECLINED_ERROR':
      return ErrorCode.PAYMENT_DECLINED_ERROR;
    case 'ALREADY_LOGGED_IN_ERROR':
      return ErrorCode.ALREADY_LOGGED_IN_ERROR;
    case 'MISSING_PASSWORD_ERROR':
      return ErrorCode.MISSING_PASSWORD_ERROR;
    case 'PASSWORD_VALIDATION_ERROR':
      return ErrorCode.PASSWORD_VALIDATION_ERROR;
    case 'PASSWORD_ALREADY_SET_ERROR':
      return ErrorCode.PASSWORD_ALREADY_SET_ERROR;
    case 'VERIFICATION_TOKEN_INVALID_ERROR':
      return ErrorCode.VERIFICATION_TOKEN_INVALID_ERROR;
    case 'VERIFICATION_TOKEN_EXPIRED_ERROR':
      return ErrorCode.VERIFICATION_TOKEN_EXPIRED_ERROR;
    case 'IDENTIFIER_CHANGE_TOKEN_INVALID_ERROR':
      return ErrorCode.IDENTIFIER_CHANGE_TOKEN_INVALID_ERROR;
    case 'IDENTIFIER_CHANGE_TOKEN_EXPIRED_ERROR':
      return ErrorCode.IDENTIFIER_CHANGE_TOKEN_EXPIRED_ERROR;
    case 'PASSWORD_RESET_TOKEN_INVALID_ERROR':
      return ErrorCode.PASSWORD_RESET_TOKEN_INVALID_ERROR;
    case 'PASSWORD_RESET_TOKEN_EXPIRED_ERROR':
      return ErrorCode.PASSWORD_RESET_TOKEN_EXPIRED_ERROR;
    case 'NOT_VERIFIED_ERROR':
      return ErrorCode.NOT_VERIFIED_ERROR;
    default:
      return ErrorCode.UNKNOWN_ERROR;
  }
}
