name: hyperce
description: It is about a complete ecommerce app for Android and iOS. 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5  

  # Allows creating swipeable card interfaces.
  card_swiper: ^3.0.1

  # Offers a staggered grid view layout for arranging widgets.
  flutter_staggered_grid_view: ^0.7.0

  # Implements a rubber transition effect for UI elements.
  rubber: ^1.0.1
  
  # Provides a customizable PIN code input text field.
  pin_code_text_field: ^1.8.0

  # Enables HTTP network requests and responses.
  http: ^1.0.0

  # Displays a rating bar widget for user ratings.
  flutter_rating_bar: ^4.0.0

  # Offers internationalization and localization support.
  intl: ^0.18.1

  # Provides a customizable number picker widget.
  numberpicker: ^2.1.1

  # Renders SVG images in Flutter.
  flutter_svg: ^2.0.2

  # Helps in adapting UI elements to different screen sizes.
  flutter_screenutil: ^5.5.2

  # Adds various page transition animations.
  page_transition: ^2.0.5

  # Simplifies state management and navigation.
  get: ^4.6.5

  # Offers a collection of loading indicators.
  flutter_spinkit: ^5.2.0

  # Caches network images to improve performance.
  cached_network_image: ^3.2.0

  # Displays a star rating widget.
  flutter_rating_stars: ^1.0.3+4

  # Creates introductory sliders for user onboarding.
  intro_slider: ^4.2.0

  # Integrates Hive database with Flutter.
  hive_flutter: ^1.1.0

  # A lightweight and efficient database solution.
  hive: ^2.2.2

  # Generates onboarding sliders for user guidance.
  flutter_onboarding_slider: ^1.0.9

  # Generates app launcher icons for Android and iOS.
  flutter_launcher_icons: ^0.13.1

  # Integrates GraphQL queries with Flutter.
  graphql_flutter: ^5.1.2

  # Adds staggered animations to widgets.
  flutter_staggered_animations: ^1.1.1

  # Implements shimmering effect placeholders.
  shimmer: ^3.0.0

  # Allows easy integration of Google Fonts.
  google_fonts: ^5.1.0
  
  # Displays toast messages in Flutter apps.
  fluttertoast: ^8.2.2

  # Provides a modal progress indicator.
  modal_progress_hud_nsn: ^0.5.1

  # Includes Feather icons in your app.
  flutter_feather_icons: ^2.0.0+1

  # Integrates Material Design icons.
  material_design_icons_flutter: ^7.0.7296

  # Adds customizable notifications.
  awesome_notifications: ^0.8.2

  # Converts DateTime objects to a "time ago" format.
  timeago: ^3.3.0
  
  # Gives new style for TabBarview
  google_nav_bar: ^5.0.6

  json_annotation: any
  flutter_map: ^6.1.0
  latlong2: any
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Runs code generation for Flutter projects.
  build_runner: ^2.0.4

  # Generates code for JSON serialization and deserialization.
  json_serializable: ^6.6.1

# Configuration for app icons
flutter_icons:
  android: "launcher_icon" # Name of default icon in android project
  ios: true # Include ios platform icons
  image_path: "assets/images/logo.png" # Path to your image file


# The following section is specific to Flutter.
flutter:

  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
  - assets/images/
  - assets/icons/

  fonts:
  - family: CS_Rocky
    fonts:
    - asset: fonts/CSRockyRegular.ttf
  - family: RocaOne
    fonts:
    - asset: fonts/RocaOne-Rg.ttf
  - family: Poppins
    fonts:
    - asset: fonts/Poppins.ttf
  - family: Inter
    fonts:
    - asset: fonts/Inter.ttf
  - family: GeneralSans
    fonts:
    - asset: fonts/GeneralSans.ttf

